# Generated by Django 5.0.2 on 2024-02-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='name_plural',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='rounding',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='currency',
        ),
        migrations.AddField(
            model_name='trip',
            name='country_currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='user_currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
